plugins:
  streamers_enabled:
    default: true
    client: true

  streamers_group_name:
    default: "Streamers"
    client: true

  streamers_min_trust_level:
    default: 2
    type: integer
    client: false

  streamers_auto_manage_group:
    default: false
    type: bool
    client: false

  streamers_icecast_status_url:
    default: ""
    client: false

  streamers_icecast_basic_auth_user:
    default: ""
    client: false

  streamers_icecast_basic_auth_password:
    default: ""
    secret: true
    client: false

  streamers_streams_page_requires_login:
    default: true
    type: bool
    client: true

  streamers_chat_topic_id:
    default: 0
    type: integer
    client: false

  streamers_icecast_source_auth_enabled:
    default: false
    type: bool
    client: false

  streamers_icecast_source_auth_shared_secret:
    default: ""
    secret: true
    client: false
